### ISSUE TITLE
Can you support Juniper config with JUNOS

### ISSUE THREAD

**Issue by zenfas** [rmerzlyakov/putty_hlsyn#1]
The same on title 
Thank you :)

**Comment by rmerzlyakov** [comment]
I'm sorry but I don't plan to.
Juniper has very different syntax from Cisco and Huawei. I do not know it well, and i don't have access to any device with JunOS.
--
Отправлено из Mail.ru для Android четверг, 20 октября 2022г., 19:17 +07:00 от zenfas  ***@***.*** :

**Comment by zenfas** [comment]
> I'm sorry but I don't plan to. Juniper has very different syntax from Cisco and Huawei. I do not know it well, and i don't have access to any device with JunOS. -- Отправлено из Mail.ru для Android четверг, 20 октября 2022г., 19:17 +07:00 от zenfas ***@***.*** :
> […](#)
> The same on title Thank you :) — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you are subscribed to this thread. Message ID: @ github . com>

How about support highlight for IPv6?

**Comment by rmerzlyakov** [comment]
Ok, i'll try later.
--
Отправлено из Mail.ru для Android пятница, 21 октября 2022г., 08:05 +07:00 от zenfas  ***@***.*** :

**Comment by rmerzlyakov** [comment]
New version of PuTTY with IPv6 highlight ready.

**Comment by rmerzlyakov** [comment]
Closed
